on: [push, pull_request]

env:
    APT_INSTALL: env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends


jobs:
    focal_test:
        runs-on: ubuntu-latest
        container: ubuntu:focal
        steps:
            - uses: actions/checkout@v5
            - run: apt update && ${APT_INSTALL} make wget sudo build-essential python3-pip
            - run: make install_ubuntu_test_deps
            - run: make test

    jammy_test:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v5
            - run: make install_ubuntu_test_deps
            - run: make test

    noble_test:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v5
            - run: make install_ubuntu_test_deps
            - run: make test

    resolute_test:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v5
            - run: make install_ubuntu_test_deps
            - run: make test

    deb:
        runs-on: ubuntu-26.04
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v5
            - run: make deb_install_deps
            - run: make deb_any
            - run: sudo dpkg -i build/thread_supervisor-*-any.deb

    resolute_ccws:
        container: asherikov/ccws:resolute
        runs-on: ubuntu-latest
        env:
            WORKSPACE_SRC: ${GITHUB_WORKSPACE}
        steps:
            - uses: actions/checkout@v5
            - run: mkdir -p "${WORKSPACE_SRC}/.ccws/"
            - run: echo 'set(thread_supervisor_TESTS "ON" CACHE STRING "" FORCE)' > "${WORKSPACE_SRC}/.ccws/toolchain.cmake"
            # g++-16 -- to be fixed in ccws
            - run: |
                cd /ccws
                sudo apt update
                sudo ${APT_INSTALL} g++-16
                make BUILD_PROFILE=static_checks
                make dep_install PKG=thread_supervisor
                make thread_supervisor BUILD_PROFILE=scan_build

