on: [push, pull_request]

jobs:
    focal_test:
        runs-on: ubuntu-20.04

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v3
            - run: make install_ubuntu_test_deps
            - run: make test

    jammy_test:
        runs-on: ubuntu-22.04

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v3
            - run: make install_ubuntu_test_deps
            - run: make test
