on:
    push:
        tags:
            - 1.**

env:
    APT: sudo apt install -y --no-install-recommends

jobs:
    deb_cloudsmith:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - run: make deb_install_deps_cloudsmith
            - run: env CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }} make deb_cloudsmith_any
