on:
    push:
        tags:
            - 1.**

env:
    APT: sudo apt install -y --no-install-recommends

jobs:
    bionic_deb_cloudsmith:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - run: make install_cloudsmith_deps
            - run: env CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }} make deb-cloudsmith
